--FEATURES BRAINSTORM


----TAB 'APPLICATION_TRAIN/TEST' (PERSON ID LEVEL SK_ID_CURR)

----TAB 'BUREAU' (SINGLE CONTRACT LEVEL SK_ID_BUREAU) (PHAI GOM VE LEVEL SK_ID_CURR)
------CREDIT_ACTIVE: COUNT_ACC_ACTIVE/ALL/BAD_DEBT/SOLD, RATE_ACTIVE_(BAD_DEBT OR SOLD)/ALL
------CREDIT_CURRENCY:
----------currency 4	10
----------currency 3	174
----------currency 2	1224
----------currency 1	1715020
------DAYS_CREDIT: MIN_MAX_MEAN_DAYS_LAST_INQ
------CREDIT_DAY_OVERDUE: MIN_MAX_MEAN_CREDIT_DAY_OVERDUE
------DAYS_CREDIT_ENDDATE: MIN_MAX_MEAN_DAYS_CREDIT_ENDDATE (***CO THE BI LOI DU LIEU KHI NHAP LIEU EXCEL) --CHUA XU LY
------DAYS_ENDDATE_FACT: MIN_MAX_MEAN_DAYS_ENDDATE_FACT (***CO THE BI LOI DU LIEU KHI NHAP LIEU EXCEL) --CHUA XU LY
------AMT_CREDIT_MAX_OVERDUE: MIN_MAX_MEAN_AMT_CREDIT_MAX_OVERDUE
------CNT_CREDIT_PROLONG: BINARY_PROLONG/NOT, ALL_PROLONG_LIFETIME
------AMT_CREDIT_SUM: MIN_MAX_MEAN_AMT_CREDIT_SUM, AMT_PER_MONTH
------AMT_CREDIT_SUM_DEBT: MIN_MAX_MEAN_AMT_CREDIT_SUM_DEBT, AMT_PER_MTHS
------AMT_CREDIT_SUM_LIMIT: MIN_MAX_MEAN_AMT_CREDIT_SUM_LIMIT, MIN_MAX_MEAN_TOTAL_AMT_DEBT_LIMIT, AMT_PER_MTHS
------AMT_CREDIT_SUM_OVERDUE: MIN_MAX_MEAN_AMT_OVERDUE/TOTAL_LIMIT, MIN_MAX_MEAN_AMT_OVERDUE/TOTAL_DEBT
------CREDIT_TYPE: (***DUNG LAM FILTER CHO NHUNG FEATURE TREN, DU KIEN LAM K-MEAN SEGMENT FILTER DO CO NHIEU TYPE) --CHUA XU LY
----------Interbank credit									  1
----------Mobile operator loan								  1
----------Loan for purchase of shares (margin lending)		  4
----------Loan for the purchase of equipment				 19
----------Real estate loan									 27
----------Cash loan (non-earmarked)							 56
----------Loan for working capital replenishment	        469
----------Unknown type of loan							    555
----------Another type of loan							   1017
----------Loan for business development              	   1975
----------Microloan										  12413
----------Mortgage										  18391
----------Car loan										  27690
----------Credit card									 402195
----------Consumer credit								1251615
------DAYS_CREDIT_UPDATE (NGAY GAN NHAT PULL BAN GHI CIC/PCB): 
------AMT_ANNUITY: SUM, MIN_MAX_MEAN_AMT_ANNUITY

----TAB 'BUREAU_BALANCE' (CIC/PCB MONTHLY REPORT SNAPSHOT LEVEL) (PHAI GOM VE LEVEL SK_ID_BUREAU) (PHAI GOM VE LEVEL SK_ID_CURR)
------MONTHS_BALANCE: MTHS_SINCE_LAST_PAST_DUE, PAST_DUE_FREQ
------STATUS: NO_PAST_DUE(12345)_3M_6M_1Y_3Y_ALL, MEAN_DPD_TIME_WEIGHT, MAX_MIN_MEAN_DPD_3M_6M_1Y_3Y_ALL
----------0	7499507
----------1	242347
----------2	23419
----------3	8924
----------4	5847
----------5	62406
----------C	13646993
----------X	5810482

--* NOTES: CHI MAP DUOC 47.62% RECORD BUREAU BALANCE

WITH BUREAU_DETAIL_1 AS (
    SELECT 
        *,
        LAG(b.DAYS_CREDIT, 1) OVER (PARTITION BY b.SK_ID_CURR ORDER BY b.DAYS_CREDIT ASC) AS LAG_DAYS_CREDIT,
        CASE WHEN CREDIT_TYPE NOT IN ('Microloan', 'Mortgage', 'Car loan', 'Credit card', 'Consumer credit') THEN 'Others' ELSE CREDIT_TYPE END AS CREDIT_TYPE_TRANS
    FROM dbo.bureau b
),

BUREAU_DETAIL AS (
    SELECT
		SK_ID_CURR,

		COUNT(CREDIT_ACTIVE) OVER (PARTITION BY SK_ID_CURR) AS COUNT_CREDIT_STATUS_ALL,
		SUM(CASE WHEN CREDIT_ACTIVE = 'Active' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS COUNT_CREDIT_STATUS_ACTIVE,
		SUM(CASE WHEN CREDIT_ACTIVE IN ('Bad debt', 'Sold') THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS COUNT_CREDIT_STATUS_BADDEBT,
		MIN(DAYS_CREDIT) OVER (PARTITION BY SK_ID_CURR) AS INIT_CREDIT_INQ_DAYS,
		MAX(DAYS_CREDIT) OVER (PARTITION BY SK_ID_CURR) AS LAST_CREDIT_INQ_DAYS,
		AVG(CAST(DAYS_CREDIT AS FLOAT)) OVER (PARTITION BY SK_ID_CURR) AS MEAN_CREDIT_INQ_DAYS,
		MIN(CREDIT_DAY_OVERDUE) OVER (PARTITION BY SK_ID_CURR) AS MIN_DPD,
		MAX(CREDIT_DAY_OVERDUE) OVER (PARTITION BY SK_ID_CURR) AS MAX_DPD,
		AVG(CAST(CREDIT_DAY_OVERDUE AS FLOAT)) OVER (PARTITION BY SK_ID_CURR) AS MEAN_DPD,
		SUM(CNT_CREDIT_PROLONG) OVER (PARTITION BY SK_ID_CURR) AS COUNT_PROLONGED_LIFETIME,
		SUM(CASE WHEN CNT_CREDIT_PROLONG > 0 THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS IS_PROLONGED,
		MIN(DAYS_CREDIT_UPDATE) OVER (PARTITION BY SK_ID_CURR) AS MIN_DAYS_CREDIT_UPDATE,
		MAX(DAYS_CREDIT_UPDATE) OVER (PARTITION BY SK_ID_CURR) AS MAX_DAYS_CREDIT_UPDATE,
		AVG(CAST(DAYS_CREDIT_UPDATE AS FLOAT)) OVER (PARTITION BY SK_ID_CURR) AS MEAN_DAYS_CREDIT_UPDATE,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MICROLOAN_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MORTGAGE_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CAR_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CC_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CONSUMER_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_OTHERS_C1,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MICROLOAN_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MORTGAGE_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CAR_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CC_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CONSUMER_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_OTHERS_C2,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MICROLOAN_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MORTGAGE_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CAR_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CC_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CONSUMER_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_OTHERS_C3,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MICROLOAN_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_MORTGAGE_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CAR_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CC_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_CONSUMER_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_MAX_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_MAX_OVERDUE_OTHERS_C4,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MICROLOAN_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MORTGAGE_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CAR_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CC_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CONSUMER_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OTHERS_C1,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MICROLOAN_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MORTGAGE_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CAR_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CC_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CONSUMER_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OTHERS_C2,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MICROLOAN_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MORTGAGE_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CAR_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CC_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CONSUMER_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OTHERS_C3,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MICROLOAN_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_MORTGAGE_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CAR_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CC_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_CONSUMER_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OTHERS_C4,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MICROLOAN_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MORTGAGE_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CAR_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CC_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CONSUMER_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_OTHERS_C1,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MICROLOAN_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MORTGAGE_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CAR_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CC_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CONSUMER_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_OTHERS_C2,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MICROLOAN_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MORTGAGE_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CAR_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CC_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CONSUMER_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_OTHERS_C3,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MICROLOAN_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_MORTGAGE_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CAR_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CC_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_CONSUMER_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_DEBT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_DEBT_OTHERS_C4,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MICROLOAN_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MORTGAGE_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CAR_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CC_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CONSUMER_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_OTHERS_C1,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MICROLOAN_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MORTGAGE_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CAR_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CC_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CONSUMER_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_OTHERS_C2,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MICROLOAN_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MORTGAGE_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CAR_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CC_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CONSUMER_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_OTHERS_C3,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MICROLOAN_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_MORTGAGE_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CAR_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CC_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_CONSUMER_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_LIMIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_LIMIT_OTHERS_C4,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MICROLOAN_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MORTGAGE_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CAR_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CC_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CONSUMER_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_OTHERS_C1,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MICROLOAN_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MORTGAGE_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CAR_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CC_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CONSUMER_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_OTHERS_C2,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MICROLOAN_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MORTGAGE_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CAR_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CC_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CONSUMER_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_OTHERS_C3,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MICROLOAN_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_MORTGAGE_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CAR_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CC_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_CONSUMER_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_CREDIT_SUM_OVERDUE ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_CREDIT_SUM_OVERDUE_OTHERS_C4,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MICROLOAN_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MORTGAGE_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CAR_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CC_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CONSUMER_C1,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 1' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_OTHERS_C1,

		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MICROLOAN_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MORTGAGE_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CAR_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CC_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CONSUMER_C2,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 2' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_OTHERS_C2,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MICROLOAN_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MORTGAGE_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CAR_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CC_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CONSUMER_C3,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 3' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_OTHERS_C3,
		
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Microloan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MICROLOAN_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Mortgage' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_MORTGAGE_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Car loan' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CAR_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Credit card' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CC_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Consumer credit' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_CONSUMER_C4,
		SUM(CASE WHEN CREDIT_TYPE_TRANS = 'Others' AND CREDIT_CURRENCY = 'currency 4' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS AMT_ANNUITY_OTHERS_C4

    FROM BUREAU_DETAIL_1
),

MAP_B_1 AS (
    SELECT 
        *,
        CAST(COUNT_CREDIT_STATUS_ACTIVE AS FLOAT) / NULLIF(COUNT_CREDIT_STATUS_ALL, 0) AS RATE_ACTIVE,
        CAST(COUNT_CREDIT_STATUS_BADDEBT AS FLOAT) / NULLIF(COUNT_CREDIT_STATUS_ALL, 0) AS RATE_BADDEBT
    FROM BUREAU_DETAIL
),

MAP_B AS (
	SELECT DISTINCT * FROM MAP_B_1
)

SELECT * FROM dbo.application_train ATR
LEFT JOIN MAP_B ON ATR.SK_ID_CURR = MAP_B.SK_ID_CURR


------

--SELECT * FROM dbo.previous_application PA
--LEFT JOIN dbo.installments_payments IPS ON PA.SK_ID_PREV = IPS.SK_ID_PREV
--LEFT JOIN dbo.credit_card_balance CCB ON PA.SK_ID_PREV = CCB.SK_ID_PREV
--WHERE PA.SK_ID_PREV = '1000521'

--SELECT COUNT(*) FROM dbo.previous_application

--SELECT NAME_CONTRACT_TYPE, COUNT(NAME_CONTRACT_TYPE) FROM dbo.previous_application GROUP BY NAME_CONTRACT_TYPE

--SELECT TOP(100) * FROM dbo.previous_application PA
--LEFT JOIN dbo.installments_payments IPS ON PA.SK_ID_PREV = IPS.SK_ID_PREV

--SELECT * FROM dbo.previous_application WHERE NAME_CONTRACT_TYPE = 'Revolving loans' ORDER BY SK_ID_PREV

--SELECT PA.PRODUCT_COMBINATION, PA.NAME_CONTRACT_TYPE, CCB.* FROM dbo.credit_card_balance CCB 
--LEFT JOIN dbo.previous_application PA ON CCB.SK_ID_PREV = PA.SK_ID_PREV
--WHERE PA.NAME_CONTRACT_TYPE = 'Revolving loans'
--ORDER BY CCB.MONTHS_BALANCE