SELECT FLAG_LAST_APPL_PER_CONTRACT, COUNT(FLAG_LAST_APPL_PER_CONTRACT) FROM dbo.previous_application GROUP BY FLAG_LAST_APPL_PER_CONTRACT

SELECT PA1.SK_ID_PREV, PA1.FLAG_LAST_APPL_PER_CONTRACT, PA2.FLAG_LAST_APPL_PER_CONTRACT
FROM dbo.previous_application PA1
INNER JOIN dbo.previous_application PA2 ON PA1.SK_ID_PREV = PA2.SK_ID_PREV
WHERE PA1.FLAG_LAST_APPL_PER_CONTRACT = 'N' AND PA2.FLAG_LAST_APPL_PER_CONTRACT = 'Y'
ORDER BY PA1.SK_ID_PREV, PA2.SK_ID_PREV

SELECT SK_ID_PREV FROM dbo.previous_application WHERE FLAG_LAST_APPL_PER_CONTRACT = 'N'
--2770539
--2139354
--2470545
--2319125
--2195939
--2285603

SELECT * FROM dbo.previous_application WHERE SK_ID_CURR = '185661' ORDER BY SK_ID_PREV