--SELECT CHANNEL_TYPE, COUNT(CHANNEL_TYPE) FROM dbo.previous_application GROUP BY CHANNEL_TYPE ORDER BY CHANNEL_TYPE
----AP+ (Cash loan)			       57046
----Car dealer					     452
----Channel of corporate sales	    6150
----Contact center			       71297
----Country-wide				  494690
----Credit and cash offices	      719968
----Regional / Local			  108528
----Stone						  212083

--SELECT NAME_PORTFOLIO, COUNT(NAME_PORTFOLIO) FROM dbo.previous_application GROUP BY NAME_PORTFOLIO ORDER BY NAME_PORTFOLIO
----Cards	144985
----Cars	   425
----Cash	461563
----POS	691011
----XNA	372230

--SELECT NAME_YIELD_GROUP, COUNT(NAME_YIELD_GROUP) FROM dbo.previous_application GROUP BY NAME_YIELD_GROUP ORDER BY NAME_YIELD_GROUP
----high	    353331
----low_action	 92041
----low_normal	322095
----middle	    385532
----XNA	        517215

--SELECT NFLAG_INSURED_ON_APPROVAL, COUNT(NFLAG_INSURED_ON_APPROVAL) FROM dbo.previous_application GROUP BY NFLAG_INSURED_ON_APPROVAL ORDER BY NFLAG_INSURED_ON_APPROVAL

--SELECT NAME_CONTRACT_TYPE, NAME_CONTRACT_STATUS, COUNT(*) FROM dbo.previous_application GROUP BY NAME_CONTRACT_TYPE, NAME_CONTRACT_STATUS ORDER BY NAME_CONTRACT_TYPE, NAME_CONTRACT_STATUS
----Cash loans	    Approved	  312540
----Cash loans	    Canceled	  268591
----Cash loans	    Refused	      165928
----Cash loans	    Unused offer	 494
----Consumer loans	Approved	  626470
----Consumer loans	Canceled	    1559
----Consumer loans	Refused	       75185
----Consumer loans	Unused offer   25937
----Revolving loans	Approved	   97771
----Revolving loans	Canceled	   45854
----Revolving loans	Refused	       49534
----Revolving loans	Unused offer	   5
----XNA	            Canceled	     315
----XNA	            Refused	          31

WITH PA_AGG AS (
	SELECT SK_ID_CURR,
	       ROW_NUMBER() OVER (PARTITION BY SK_ID_CURR ORDER BY SK_ID_PREV) RN,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMANN_CASH_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMANN_CASH_APPROVED,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMANN_CONSUMER_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMANN_CONSUMER_APPROVED,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMANN_REVOLVE_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMANN_REVOLVE_APPROVED,

		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMANN_CASH_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMANN_CASH_ALL,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMANN_CONSUMER_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMANN_CONSUMER_ALL,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMANN_REVOLVE_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN AMT_ANNUITY ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMANN_REVOLVE_ALL,

		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMCRED_CASH_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMCRED_CASH_APPROVED,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMCRED_CONSUMER_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMCRED_CONSUMER_APPROVED,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMCRED_REVOLVE_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMCRED_REVOLVE_APPROVED,

		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMCRED_CASH_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMCRED_CASH_ALL,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMCRED_CONSUMER_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMCRED_CONSUMER_ALL,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMCRED_REVOLVE_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN AMT_CREDIT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMCRED_REVOLVE_ALL,

		   MAX(AMT_APPLICATION - AMT_CREDIT) OVER (PARTITION BY SK_ID_CURR) AS MAX_DIFF_APP_CREDIT,
		   AVG(AMT_APPLICATION - AMT_CREDIT) OVER (PARTITION BY SK_ID_CURR) AS MEAN_DIFF_APP_CREDIT,
		   
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMDOWN_CASH_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMDOWN_CASH_APPROVED,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMDOWN_CONSUMER_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMDOWN_CONSUMER_APPROVED,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMDOWN_REVOLVE_APPROVED,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' AND NAME_CONTRACT_STATUS = 'Approved' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMDOWN_REVOLVE_APPROVED,

		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMDOWN_CASH_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMDOWN_CASH_ALL,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMDOWN_CONSUMER_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMDOWN_CONSUMER_ALL,
		   MAX(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MAX_AMDOWN_REVOLVE_ALL,
		   AVG(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN AMT_DOWN_PAYMENT ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS MEAN_AMDOWN_REVOLVE_ALL,

		   MIN(CASE WHEN NAME_CONTRACT_TYPE = 'Cash loans' THEN DAYS_DECISION ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS EARLIEST_CR_LINE_CASH,
		   MIN(CASE WHEN NAME_CONTRACT_TYPE = 'Consumer loans' THEN DAYS_DECISION ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS EARLIEST_CR_LINE_CONSUMER,
		   MIN(CASE WHEN NAME_CONTRACT_TYPE = 'Revolving loans' THEN DAYS_DECISION ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS EARLIEST_CR_LINE_REVOLVE,

		   SUM(CASE WHEN NAME_YIELD_GROUP = 'high' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS NUM_HIGH_YIELD,
		   SUM(CASE WHEN NAME_YIELD_GROUP = 'low_action' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS NUM_LOW_ACTION_YIELD,
		   SUM(CASE WHEN NAME_YIELD_GROUP = 'low_normal' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS NUM_LOW_NORMAL_YIELD,
		   SUM(CASE WHEN NAME_YIELD_GROUP = 'middle' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS NUM_MIDDLE_YIELD,
		   SUM(CASE WHEN NAME_YIELD_GROUP = 'XNA' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS NUM_UNK_YIELD,

		   SUM(CASE WHEN NFLAG_INSURED_ON_APPROVAL = '1' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS NUM_INSURED,

		   SUM(CASE WHEN SELLERPLACE_AREA = '-1' THEN 1 ELSE 0 END) OVER (PARTITION BY SK_ID_CURR) AS IS_AREA_1
	FROM dbo.previous_application
)

SELECT * 
--INTO dbo.pa_agg
FROM PA_AGG WHERE RN = 1